### PR TITLE
fix ioctl example erro (_IOW needed instead _IOR)

### PR DESCRIPTION
**Pull request by SunyDays**
- remove flycheck file from 4.9.11 examples directory
- rename file_sched.c to sched.c according to text of the book
- adding intrpt.c file (example from book)
- minor typo fixes

### CODE REVIEW

**Comment by bashrc** [comment]
Looks like there are various compile errors in intrpt.c

**Comment by SunyDays** [comment]
Quote from book:
** Keyboards on the Intel Architecture
The rest of this chapter is completely Intel specific. If you're not running on an Intel platform, it will not work. Don't even try to compile the code here. Move right along, nothing to see.

Because of it I don't add intptr.c to Makefile. I will try to find out what is wrong with this code then I will read this chapter

**Comment by bashrc** [comment]
Ok, but I'm running an intel based system and still getting compile errors.

**Comment by SunyDays** [comment]
I suupose, this example not compiled since 2001:) Very nice that you update this example

**Pull request merged**
